-- 1. Tabela de Álbuns
CREATE TABLE IF NOT EXISTS public.albuns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    titulo TEXT NOT NULL,
    capa_url TEXT
);

-- 2. Tabela de Fotos da Galeria
CREATE TABLE IF NOT EXISTS public.fotos_galeria (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    album_id BIGINT REFERENCES public.albuns(id) ON DELETE CASCADE,
    url TEXT NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.albuns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fotos_galeria ENABLE ROW LEVEL SECURITY;

-- Policies de Leitura (Públicas)
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'albuns' AND policyname = 'Leitura pública de álbuns') THEN
        CREATE POLICY "Leitura pública de álbuns" ON public.albuns FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'fotos_galeria' AND policyname = 'Leitura pública de fotos') THEN
        CREATE POLICY "Leitura pública de fotos" ON public.fotos_galeria FOR SELECT USING (true);
    END IF;

    -- Policies de Escrita (Apenas Autenticados)
    -- Álbuns
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'albuns' AND policyname = 'Admin gere álbuns') THEN
        CREATE POLICY "Admin gere álbuns" ON public.albuns FOR ALL TO authenticated USING (true);
    END IF;

    -- Fotos
    IF NOT EXISTS (SELECT FROM pg_policies WHERE tablename = 'fotos_galeria' AND policyname = 'Admin gere fotos') THEN
        CREATE POLICY "Admin gere fotos" ON public.fotos_galeria FOR ALL TO authenticated USING (true);
    END IF;
END $$;
